name: EpiCook
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  cloud_functions: ^4.1.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.2.2
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_dotenv: ^5.0.0
  flutter_modular: ^5.0.3
  flutter_swiper: ^1.1.6
  flutter_typeahead: ^4.3.7
  flutterfire_cli: ^0.2.6
  fluttertoast: ^8.2.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  google_sign_in: ^6.1.0
  http: ^0.13.4
  intl_utils: ^2.8.2
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.1.1

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - .env
    - assets/images/

  uses-material-design: true
